---
# Prometheus (VMSingle) IngressRoute — INTERNAL ONLY
# Accessible at http://prometheus.lab.jamilshaikh.in from LAN
# Service: vmsingle-victoria-metrics-victoria-metrics-k8s-stack (victor-metrics-k8s-stack chart)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.lab.jamilshaikh.in`)
      kind: Rule
      services:
        - name: vmsingle-victoria-metrics-victoria-metrics-k8s-stack
          port: 8428
