---
# Kustomize entry point for all Flux-managed apps
# Add new app manifests/HelmReleases to this directory and reference them here
resources:
  - namespaces.yaml
  - metrics-server.yaml
  - kube-prometheus-stack.yaml
  - defectdojo.yaml
  - trivy-operator.yaml
