apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autofix-dojo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: autofix-dojo
    server: https://kubernetes.default.svc
  project: default
  sources:
    # Namespace and secrets from git
    - repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops
      path: gitops/manifests/autofix-dojo
      targetRevision: master
    # Helm chart from autofix-dojo repo
    - repoURL: https://github.com/jamilshaikh07/autofix-dojo
      path: deploy/helm-chart
      targetRevision: master
      helm:
        values: |
          image:
            repository: ghcr.io/jamilshaikh07/autofix-dojo
            tag: "sha-6a642c5"
            pullPolicy: Always

          # Disable controller mode - use CronJobs
          controller:
            enabled: false

          # DefectDojo - disabled for now (will enable when DefectDojo is deployed)
          defectdojo:
            enabled: false

          # Git Configuration for PR creation
          git:
            enabled: true
            repoUrl: "https://github.com/jamilshaikh07/talos-proxmox-gitops"
            mainBranch: "master"
            platform: "github"
            existingSecret: "autofix-dojo-github"

          # Helm Chart Scanning
          helm:
            enabled: true
            scanPath: "/gitops"
            scanInterval: "24h"
            # Auto PR creation - like Dependabot but for Helm!
            autoPR:
              enabled: true
              schedule: "0 0 * * 1"  # Weekly on Monday at midnight
              priority: "minor"       # Create PRs for minor+ (includes critical, major, minor)
              repoOwner: "jamilshaikh07"
              repoName: "talos-proxmox-gitops"
              scanPath: "gitops/apps"

          # Scan Schedule
          schedule:
            vulnerabilities: "0 6 * * *"   # Daily at 6 AM
            helmDrift: "0 0 * * 1"         # Weekly on Monday

          # SLO tracking
          slo:
            enabled: true
            dbPath: "/data/slo_data.json"

          # Persistence - use longhorn
          persistence:
            enabled: true
            storageClass: "longhorn"
            size: 1Gi

          # Resources for homelab
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi

          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false

          # Web Dashboard
          web:
            enabled: true
            replicas: 1
            port: 8080
            service:
              type: ClusterIP
              port: 80
            ingress:
              enabled: true
              className: "cilium"
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              hosts:
                - host: autofix.homelab.local
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - secretName: autofix-tls
                  hosts:
                    - autofix.homelab.local

          # Metrics for Prometheus/Grafana
          metrics:
            enabled: true
            port: 9090
            serviceMonitor:
              enabled: true
              interval: 30s

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
