apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homelab
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: homarr
    repoURL: https://homarr-labs.github.io/charts
    targetRevision: 8.4.3
    helm:
      values: |
        env:
          TZ: "Asia/Kolkata"

        # Persistence for database (SQLite) and icons/assets
        persistence:
          homarrDatabase:
            enabled: true
            name: "homarr-db-pvc-data"
            storageClassName: "local-path"
            accessModes: "ReadWriteOnce"
            size: 500Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
