apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homelab
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: homarr
    repoURL: https://homarr-labs.github.io/charts
    targetRevision: 8.3.0
    helm:
      values: |
        # Homarr - Homelab start page / dashboard (v8.3.0)

        # Environment variables (key-value format for v8.x)
        env:
          TZ: "Asia/Kolkata"
          LOG_LEVEL: "info"
          AUTH_PROVIDERS: "credentials"
          AUTH_SESSION_EXPIRY_TIME: "30d"

        # Database - use PostgreSQL from homelab-pg cluster
        database:
          type: postgresql
          migrationEnabled: true

        # Database credentials from PGO secret
        envSecrets:
          dbCredentials:
            existingSecret: "homelab-pg-pguser-homarr"
            dbUrlKey: "uri"
          dbEncryption:
            existingSecret: ""
          authOidcCredentials:
            existingSecret: ""
          authLdapCredentials:
            existingSecret: ""

        # Persistence for icons/assets
        persistence:
          homarrIcons:
            enabled: true
            storageClassName: "nfs-client"
            size: "1Gi"

        # Resources
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
