apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.26.0
    helm:
        values: |
          # Loki - Log Aggregation System
          # Deployment mode: Simple Scalable (default, recommended for 3-node cluster)

          loki:
            # Authentication disabled for internal cluster use
            auth_enabled: false

            # Common configuration
            commonConfig:
              replication_factor: 2

            # Storage configuration - MinIO S3 backend
            storage:
              type: s3
              bucketNames:
                chunks: loki-chunks
                ruler: loki-ruler
                admin: loki-admin
              s3:
                endpoint: minio.minio-system.svc.cluster.local:9000
                region: us-east-1
                secretAccessKey: minioadmin123
                accessKeyId: minioadmin
                s3ForcePathStyle: true
                insecure: true

            # Schema configuration
            schemaConfig:
              configs:
                - from: 2024-01-01
                  store: tsdb
                  object_store: s3
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h

            # Limits configuration
            limits_config:
              retention_period: 720h  # 30 days
              max_query_series: 100000
              max_query_parallelism: 32
              split_queries_by_interval: 15m

            # Compactor configuration
            compactor:
              retention_enabled: true
              retention_delete_delay: 2h
              retention_delete_worker_count: 150

          # Deployment configuration
          deploymentMode: SimpleScalable

          # Backend (ingester, querier, query-frontend)
          backend:
            replicas: 2
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi

          # Read component
          read:
            replicas: 2
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi

          # Write component
          write:
            replicas: 2
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi
            persistence:
              enabled: true
              storageClass: nfs-client
              size: 10Gi

          # Gateway (nginx)
          gateway:
            enabled: true
            replicas: 1
            service:
              type: ClusterIP
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi

          # Monitoring
          monitoring:
            serviceMonitor:
              enabled: true
              namespace: monitoring
            selfMonitoring:
              enabled: false
              grafanaAgent:
                installOperator: false

          # Loki Canary (health checks)
          lokiCanary:
            enabled: false

          # Test configuration
          test:
            enabled: false

          # Single binary mode disabled (using SimpleScalable)
          singleBinary:
            replicas: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # monitoring namespace already exists
      - ServerSideApply=true
