apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-nodes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy with Longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops.git
    targetRevision: master
    path: gitops/manifests/longhorn-nodes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # longhorn-system already exists
      - ServerSideApply=true
