apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      # NOTE: Using external OMV NFS server at 10.20.0.229
      # Talos nodes have iscsi-tools extension which includes NFS client support
      values: |
        nfs:
          server: 10.20.0.229
          path: /export/k8s-nfs
          mountOptions:
            - nfsvers=4.1
            - rw
            - hard
            - timeo=600
            - retrans=2
        storageClass:
          name: nfs-client
          defaultClass: false
          allowVolumeExpansion: true
          reclaimPolicy: Delete
          archiveOnDelete: false
          mountOptions:
            - nfsvers=4.1
            - rw
            - hard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
