apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  # Ignore the PostgresCluster CRD due to large annotation size
  # Applied manually with: kubectl apply --server-side -k https://github.com/CrunchyData/postgres-operator-examples/kustomize/install/default
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: postgresclusters.postgres-operator.crunchydata.com
      jsonPointers:
        - /metadata/annotations
  source:
    repoURL: https://github.com/CrunchyData/postgres-operator-examples
    targetRevision: main
    path: kustomize/install/default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
