apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops
    targetRevision: master
    path: gitops/manifests/postgres-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
