apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.1
    helm:
      values: |
        # Promtail - Log Collection Agent
        # Deployed as DaemonSet to collect logs from all nodes

        # Configuration
        config:
          # Loki endpoint
          clients:
            - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
              tenant_id: 1

          # Scrape configuration
          snippets:
            # Common labels for all logs
            common:
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_node_name
                target_label: node_name
              - action: replace
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                  - namespace
                  - app
                target_label: job
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
              - action: replace
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                target_label: __path__
              - action: replace
                regex: true/(.*)
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                  - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_container_name
                target_label: __path__

            # Scrape all pods
            scrapeConfigs: |
              - job_name: kubernetes-pods
                pipeline_stages:
                  - cri: {}
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels:
                      - __meta_kubernetes_pod_controller_name
                    regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                    action: replace
                    target_label: __tmp_controller_name
                  - source_labels:
                      - __meta_kubernetes_pod_label_app_kubernetes_io_name
                      - __meta_kubernetes_pod_label_app
                      - __tmp_controller_name
                      - __meta_kubernetes_pod_name
                    regex: ^;*([^;]+)(;.*)?$
                    action: replace
                    target_label: app
                  - source_labels:
                      - __meta_kubernetes_pod_label_app_kubernetes_io_component
                      - __meta_kubernetes_pod_label_component
                    regex: ^;*([^;]+)(;.*)?$
                    action: replace
                    target_label: component
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_pod_node_name
                    target_label: node_name
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_namespace
                    target_label: namespace
                  - action: replace
                    replacement: $1
                    separator: /
                    source_labels:
                    - namespace
                    - app
                    target_label: job
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_pod_name
                    target_label: pod
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_pod_container_name
                    target_label: container
                  - action: replace
                    replacement: /var/log/pods/*$1/*.log
                    separator: /
                    source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                    target_label: __path__
                  - action: replace
                    regex: true/(.*)
                    replacement: /var/log/pods/*$1/*.log
                    separator: /
                    source_labels:
                    - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                    - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                    - __meta_kubernetes_pod_container_name
                    target_label: __path__

        # DaemonSet configuration
        daemonset:
          enabled: true

        # Resource limits
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        # Service Monitor for Prometheus
        serviceMonitor:
          enabled: true
          namespace: monitoring

        # Default volumes mounts for Kubernetes logs
        defaultVolumes:
          - name: run
            hostPath:
              path: /run/promtail
          - name: pods
            hostPath:
              path: /var/log/pods

        defaultVolumeMounts:
          - name: run
            mountPath: /run/promtail
          - name: pods
            mountPath: /var/log/pods
            readOnly: true

        # Security context
        securityContext:
          privileged: true
          runAsUser: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # monitoring namespace already exists
      - ServerSideApply=true
