apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routeplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops
    targetRevision: HEAD
    path: gitops/manifests/routeplane
  destination:
    server: https://kubernetes.default.svc
    namespace: routeplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
