apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # Secrets are managed via SOPS - decrypted and applied manually
    # This app just tracks the encrypted files for GitOps visibility
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops.git
    targetRevision: master
    path: gitops/manifests/secrets
    directory:
      recurse: false
      # Note: These are SOPS encrypted - ArgoCD will show them as OutOfSync
      # Actual secrets are applied via: sops -d file.yaml | kubectl apply -f -
  syncPolicy:
    # Manual sync only - secrets are applied via sops decrypt
    automated: null
    syncOptions:
      - CreateNamespace=true
