apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.24.1
    helm:
      values: |
        # Grafana Tempo - Tracing backend (monolithic)
        tempo:
          searchEnabled: true
          metricsGenerator:
            enabled: true
        persistence:
          enabled: true
          storageClassName: nfs-client
          size: 20Gi
        serviceMonitor:
          enabled: true
          namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # monitoring namespace already exists
      - ServerSideApply=true
