apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: test-pg
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/manifests/test-pg
    repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
