apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: uptime-kuma
    repoURL: https://helm.irsigler.cloud
    targetRevision: 2.24.0
    helm:
      values: |
        # Uptime Kuma - Uptime Monitoring & Status Page
        # Monitor all homelab services and machines

        # Persistence
        volume:
          enabled: true
          storageClassName: nfs-client  # Use storageClassName instead of storageClass
          accessMode: ReadWriteOnce
          size: 2Gi

        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
