apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: uptime-kuma
    repoURL: https://dirsigler.github.io/uptime-kuma-helm
    targetRevision: 2.23.1
    helm:
      values: |
        # Uptime Kuma - Uptime Monitoring & Status Page
        # Monitor all homelab services and machines

        # Image configuration
        image:
          repository: louislam/uptime-kuma
          tag: 1.23.15
          pullPolicy: IfNotPresent

        # Service configuration
        service:
          type: ClusterIP
          port: 3001

        # Persistence - Use Longhorn for data
        persistence:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 5Gi

        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Environment variables
        env:
          # Disable analytics
          - name: UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN
            value: "0"
          - name: UPTIME_KUMA_PORT
            value: "3001"

        # Security context
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

        # Ingress disabled (using Traefik IngressRoute)
        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
