apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: default
  sources:
    # Namespace from git
    - repoURL: https://github.com/jamilshaikh07/talos-proxmox-gitops
      path: gitops/manifests/velero-namespace
      targetRevision: master
    # Helm chart from upstream
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: "7.2.2"
      helm:
        values: |
          # Velero v4.3.0 values for Minio backend
          upgradeCRDs: false
          kubectl:
            image:
              repository: bitnami/kubectl
              tag: "latest"
          image:
            repository: velero/velero
            tag: v1.11.1
            pullPolicy: IfNotPresent
          initContainers:
            - name: velero-plugin-for-aws
              image: velero/velero-plugin-for-aws:v1.7.1
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /target
                  name: plugins
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false
          configuration:
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: velero
                default: true
                config:
                  region: minio
                  s3ForcePathStyle: "true"
                  s3Url: http://minio.minio-system.svc.cluster.local:9000
                  insecureSkipTLSVerify: "true"
            volumeSnapshotLocation:
              - name: default
                provider: aws
                config:
                  region: minio
          credentials:
            useSecret: true
            name: velero-credentials
            secretContents:
              cloud: |
                [default]
                aws_access_key_id = minioadmin
                aws_secret_access_key = minioadmin123
          deployNodeAgent: false
          schedules: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
