apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ include "postgresql-cnpg.namespace" . }}
  labels:
    {{- include "postgresql-cnpg.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.barman.s3.credentials.accessKeyId | quote }}
  ACCESS_SECRET_KEY: {{ .Values.barman.s3.credentials.secretAccessKey | quote }}
