#!/usr/bin/env python3
"""
Generate Longhorn node configurations from Terraform outputs.
This ensures all Talos nodes have Longhorn disks configured automatically.
"""

import json
import sys
from pathlib import Path

def main():
    # Read Terraform output
    terraform_json = Path(__file__).parent.parent / 'ansible' / 'terraform-inventory.json'

    if not terraform_json.exists():
        print(f"Error: {terraform_json} not found", file=sys.stderr)
        print("Run 'make terraform-apply' first", file=sys.stderr)
        sys.exit(1)

    with open(terraform_json) as f:
        terraform_data = json.load(f)

    # Get all VMs (control plane + workers)
    all_vms = terraform_data.get('all_vms', {}).get('value', {})

    if not all_vms:
        print("Error: No VMs found in Terraform output", file=sys.stderr)
        sys.exit(1)

    # Generate Longhorn node YAML
    yaml_content = """# Longhorn Node Configurations
# AUTO-GENERATED from Terraform outputs - DO NOT EDIT MANUALLY
# Generated by: scripts/generate-longhorn-nodes.py
#
# This file configures Longhorn storage disks on all Talos nodes.
# Longhorn is used exclusively for PostgreSQL databases (high-performance storage).
# All other services use NFS storage.

"""

    for node_name in sorted(all_vms.keys()):
        yaml_content += f"""---
# Longhorn Node Configuration for {node_name}
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: {node_name}
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  disks:
    default-disk:
      allowScheduling: true
      evictionRequested: false
      path: /var/mnt/longhorn
      storageReserved: 10737418240  # 10Gi reserved
      tags: []
"""

    # Write to Longhorn nodes manifest
    output_file = Path(__file__).parent.parent / 'gitops' / 'manifests' / 'longhorn-nodes' / 'nodes.yaml'
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w') as f:
        f.write(yaml_content)

    print(f"✅ Generated Longhorn nodes: {output_file}")
    print(f"   Nodes configured: {len(all_vms)}")
    for node_name in sorted(all_vms.keys()):
        print(f"     - {node_name}")

if __name__ == '__main__':
    main()
