#!/usr/bin/env python3
"""
Generate Ansible inventory from Terraform outputs.
This ensures Terraform is the single source of truth for node configuration.
"""

import json
import sys
import subprocess
from pathlib import Path

def get_ip_from_dns(hostname):
    """Get IP from DNS lookup (assumes DHCP reservation is configured)."""
    try:
        result = subprocess.run(
            ['dig', '+short', f'{hostname}.homelab.local'],
            capture_output=True,
            text=True,
            timeout=5
        )
        ip = result.stdout.strip()
        if ip and not ip.startswith(';'):
            return ip
    except Exception as e:
        print(f"Warning: Could not resolve {hostname}.homelab.local: {e}", file=sys.stderr)

    # Fallback to hardcoded IPs based on naming convention
    if 'cp-01' in hostname:
        return '10.20.0.40'
    elif 'wk-01' in hostname:
        return '10.20.0.41'
    elif 'wk-02' in hostname:
        return '10.20.0.42'
    elif 'wk-03' in hostname:
        return '10.20.0.43'
    return 'unknown'

def main():
    # Read Terraform output
    terraform_json = Path(__file__).parent.parent / 'ansible' / 'terraform-inventory.json'

    if not terraform_json.exists():
        print(f"Error: {terraform_json} not found", file=sys.stderr)
        print("Run 'make terraform-apply' first", file=sys.stderr)
        sys.exit(1)

    with open(terraform_json) as f:
        terraform_data = json.load(f)

    # Extract control plane
    controlplane_vms = terraform_data.get('controlplane_vms', {}).get('value', {})
    if not controlplane_vms:
        print("Error: No control plane VMs found in Terraform output", file=sys.stderr)
        sys.exit(1)

    cp_name = list(controlplane_vms.keys())[0]
    cp_data = controlplane_vms[cp_name]
    cp_vmid = int(cp_data['id'].split('/')[-1])
    cp_ip = get_ip_from_dns(cp_name)

    # Extract workers
    worker_vms = terraform_data.get('worker_vms', {}).get('value', {})
    workers = []

    for worker_name in sorted(worker_vms.keys()):  # Sort for consistent order
        worker_data = worker_vms[worker_name]
        worker_vmid = int(worker_data['id'].split('/')[-1])
        worker_ip = get_ip_from_dns(worker_name)

        workers.append({
            'hostname': worker_name,
            'ip': worker_ip,
            'vmid': worker_vmid
        })

    # Generate Ansible vars YAML
    ansible_vars = f"""---
# Talos Cluster Configuration Variables
# AUTO-GENERATED from Terraform outputs - DO NOT EDIT MANUALLY
# Generated by: scripts/generate-ansible-inventory.py

# Cluster configuration
cluster_name: "homelab-cluster"
cluster_endpoint: "https://{cp_ip}:6443"  # Control plane IP

# Talos node configuration (from Terraform)
talos_nodes:
  control_plane:
    hostname: "{cp_name}"
    ip: "{cp_ip}"
    vmid: {cp_vmid}
  workers:
"""

    for worker in workers:
        ansible_vars += f"""    - hostname: "{worker['hostname']}"
      ip: "{worker['ip']}"
      vmid: {worker['vmid']}
"""

    ansible_vars += """
# Proxmox configuration (for cleanup)
proxmox_node: "alif"  # Proxmox node name

# Talos configuration directory (relative to repo root)
talos_config_dir: "{{ playbook_dir }}/../../talos-{{ cluster_name }}"

# CNI to use (none = we'll install Cilium manually)
cni_name: "none"

# Allow scheduling on control plane
allow_scheduling_on_control_planes: true

# Talos version
talos_version: "1.11.5"

# Kubernetes version (must be compatible with Talos version)
kubernetes_version: "1.34.1"

# Cilium version
cilium_version: "1.16.5"

# Wait timeouts (in seconds)
wait_timeout_nodes: 600
wait_timeout_cilium: 300
"""

    # Write to Ansible vars file
    output_file = Path(__file__).parent.parent / 'ansible' / 'roles' / 'talos-cluster' / 'vars' / 'main.yml'
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w') as f:
        f.write(ansible_vars)

    print(f"✅ Generated Ansible inventory: {output_file}")
    print(f"   Control Plane: {cp_name} ({cp_ip})")
    print(f"   Workers: {len(workers)}")
    for worker in workers:
        print(f"     - {worker['hostname']} ({worker['ip']})")

if __name__ == '__main__':
    main()
