#!/usr/bin/env python3
"""
Generate Ansible inventory from Terraform outputs.
This ensures Terraform is the single source of truth for VM node configuration.
Bare metal nodes are preserved from existing config and not overwritten.
"""

import json
import sys
import subprocess
import re
from pathlib import Path

def get_ip_from_dns(hostname):
    """Get IP from DNS lookup (assumes DHCP reservation is configured)."""
    try:
        result = subprocess.run(
            ['dig', '+short', f'{hostname}.lab.jamilshaikh.in'],
            capture_output=True,
            text=True,
            timeout=5
        )
        ip = result.stdout.strip()
        if ip and not ip.startswith(';'):
            return ip
    except Exception as e:
        print(f"Warning: Could not resolve {hostname}.lab.jamilshaikh.in: {e}", file=sys.stderr)

    # Fallback to hardcoded IPs based on naming convention
    if 'cp-01' in hostname:
        return '10.20.0.40'
    elif 'wk-01' in hostname:
        return '10.20.0.41'
    elif 'wk-02' in hostname:
        return '10.20.0.42'
    elif 'wk-03' in hostname:
        return '10.20.0.43'
    return 'unknown'

def extract_baremetal_section(file_path):
    """Extract the baremetal_workers section from existing vars file if it exists."""
    if not file_path.exists():
        return None

    with open(file_path) as f:
        content = f.read()

    # Look for baremetal_workers section
    match = re.search(
        r'(# Bare metal workers.*?baremetal_workers:.*?)(?=\n# [A-Z]|\n[a-z_]+:|\Z)',
        content,
        re.DOTALL
    )
    if match:
        return match.group(1).rstrip()
    return None

def main():
    # Read Terraform output
    terraform_json = Path(__file__).parent.parent / 'ansible' / 'terraform-inventory.json'

    if not terraform_json.exists():
        print(f"Error: {terraform_json} not found", file=sys.stderr)
        print("Run 'make terraform-apply' first", file=sys.stderr)
        sys.exit(1)

    with open(terraform_json) as f:
        terraform_data = json.load(f)

    # Extract control plane
    controlplane_vms = terraform_data.get('controlplane_vms', {}).get('value', {})
    if not controlplane_vms:
        print("Error: No control plane VMs found in Terraform output", file=sys.stderr)
        sys.exit(1)

    cp_name = list(controlplane_vms.keys())[0]
    cp_data = controlplane_vms[cp_name]
    cp_vmid = int(cp_data['id'].split('/')[-1])
    cp_ip = get_ip_from_dns(cp_name)

    # Extract workers (VMs only)
    worker_vms = terraform_data.get('worker_vms', {}).get('value', {})
    workers = []

    for worker_name in sorted(worker_vms.keys()):  # Sort for consistent order
        worker_data = worker_vms[worker_name]
        worker_vmid = int(worker_data['id'].split('/')[-1])
        worker_ip = get_ip_from_dns(worker_name)

        workers.append({
            'hostname': worker_name,
            'ip': worker_ip,
            'vmid': worker_vmid
        })

    # Check for existing baremetal_workers section to preserve
    output_file = Path(__file__).parent.parent / 'ansible' / 'roles' / 'talos-cluster' / 'vars' / 'main.yml'
    baremetal_section = extract_baremetal_section(output_file)

    # Generate Ansible vars YAML
    ansible_vars = f"""---
# Talos Cluster Configuration Variables
# VM workers are AUTO-GENERATED from Terraform outputs
# Bare metal workers (baremetal_workers) are manually maintained - DO NOT DELETE
# Generated by: scripts/generate-ansible-inventory.py

# Cluster configuration
cluster_name: "homelab-cluster"
cluster_endpoint: "https://{cp_ip}:6443"  # Control plane IP

# Default install disk (used if not specified per node)
default_install_disk: "/dev/sda"

# Talos node configuration
# - install_disk: optional, defaults to default_install_disk
# - longhorn_disk: optional, dedicated disk for Longhorn storage
talos_nodes:
  control_plane:
    hostname: "{cp_name}"
    ip: "{cp_ip}"
    vmid: {cp_vmid}
    # install_disk: "/dev/sda"  # uses default
  # VM workers (from Terraform)
  workers:
"""

    for worker in workers:
        ansible_vars += f"""    - hostname: "{worker['hostname']}"
      ip: "{worker['ip']}"
      vmid: {worker['vmid']}
"""

    # Add baremetal_workers section (preserved or template)
    if baremetal_section:
        ansible_vars += f"""
{baremetal_section}
"""
        print("   ✓ Preserved existing baremetal_workers section")
    else:
        ansible_vars += """
# Bare metal workers (manually maintained - not managed by Terraform)
# Add your bare metal nodes here with custom disk configurations
# baremetal_workers:
#   - hostname: "talos-wk-04"
#     ip: "10.20.0.45"
#     install_disk: "/dev/nvme0n1"   # NVMe for Talos OS
#     longhorn_disk: "/dev/sdb"       # SSD for Longhorn storage
"""

    ansible_vars += """
# Proxmox configuration (for cleanup)
proxmox_node: "alif"  # Proxmox node name

# Talos configuration directory (relative to repo root)
talos_config_dir: "{{ playbook_dir }}/../../talos-{{ cluster_name }}"

# CNI to use (none = we'll install Cilium manually)
cni_name: "none"

# Allow scheduling on control plane
allow_scheduling_on_control_planes: true

# Talos version
talos_version: "1.11.5"

# Kubernetes version (must be compatible with Talos version)
kubernetes_version: "1.34.1"

# Cilium version
cilium_version: "1.16.5"

# Wait timeouts (in seconds)
wait_timeout_nodes: 600
wait_timeout_cilium: 300
"""

    # Write to Ansible vars file
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w') as f:
        f.write(ansible_vars)

    print(f"✅ Generated Ansible inventory: {output_file}")
    print(f"   Control Plane: {cp_name} ({cp_ip})")
    print(f"   VM Workers: {len(workers)}")
    for worker in workers:
        print(f"     - {worker['hostname']} ({worker['ip']})")

if __name__ == '__main__':
    main()
