#!/usr/bin/env python3
"""
Generate Longhorn node configurations from Terraform outputs + bare metal workers.
This ensures all Talos nodes (VMs + bare metal) have Longhorn disks configured.
"""

import json
import sys
import yaml
from pathlib import Path

def get_baremetal_workers():
    """Read bare metal workers from Ansible vars file."""
    vars_file = Path(__file__).parent.parent / 'ansible' / 'roles' / 'talos-cluster' / 'vars' / 'main.yml'

    if not vars_file.exists():
        return []

    with open(vars_file) as f:
        content = f.read()

    # Simple YAML parsing - look for baremetal_workers section
    try:
        # Remove Jinja2 templates before parsing
        clean_content = content.replace('{{ playbook_dir }}', '/tmp')
        clean_content = clean_content.replace('{{ cluster_name }}', 'homelab-cluster')
        data = yaml.safe_load(clean_content)

        if data and 'baremetal_workers' in data:
            return data['baremetal_workers'] or []
    except Exception as e:
        print(f"Warning: Could not parse baremetal_workers: {e}", file=sys.stderr)

    return []

def main():
    # Read Terraform output
    terraform_json = Path(__file__).parent.parent / 'ansible' / 'terraform-inventory.json'

    if not terraform_json.exists():
        print(f"Error: {terraform_json} not found", file=sys.stderr)
        print("Run 'make terraform-apply' first", file=sys.stderr)
        sys.exit(1)

    with open(terraform_json) as f:
        terraform_data = json.load(f)

    # Get all VMs (control plane + workers)
    all_vms = terraform_data.get('all_vms', {}).get('value', {})

    if not all_vms:
        print("Error: No VMs found in Terraform output", file=sys.stderr)
        sys.exit(1)

    # Get bare metal workers from Ansible vars
    baremetal_workers = get_baremetal_workers()

    # Generate Longhorn node YAML
    yaml_content = """# Longhorn Node Configurations
# VM nodes are AUTO-GENERATED from Terraform outputs
# Bare metal nodes are read from Ansible vars (baremetal_workers)
# Generated by: scripts/generate-longhorn-nodes.py
#
# This file configures Longhorn storage disks on all Talos nodes.
# Longhorn is used exclusively for PostgreSQL databases (high-performance storage).
# All other services use NFS storage.

"""

    # Add VM nodes
    for node_name in sorted(all_vms.keys()):
        yaml_content += f"""---
# Longhorn Node Configuration for {node_name}
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: {node_name}
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  disks:
    default-disk:
      allowScheduling: true
      evictionRequested: false
      path: /var/mnt/longhorn
      storageReserved: 10737418240  # 10Gi reserved
      tags: []
"""

    # Add bare metal nodes
    for node in baremetal_workers:
        node_name = node.get('hostname', 'unknown')
        longhorn_disk = node.get('longhorn_disk', '')
        comment = f" (bare metal - dedicated {longhorn_disk})" if longhorn_disk else " (bare metal)"

        yaml_content += f"""---
# Longhorn Node Configuration for {node_name}{comment}
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: {node_name}
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  disks:
    default-disk:
      allowScheduling: true
      evictionRequested: false
      path: /var/mnt/longhorn
      storageReserved: 10737418240  # 10Gi reserved
      tags: []
"""

    # Write to Longhorn nodes manifest
    output_file = Path(__file__).parent.parent / 'gitops' / 'manifests' / 'longhorn-nodes' / 'nodes.yaml'
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w') as f:
        f.write(yaml_content)

    total_nodes = len(all_vms) + len(baremetal_workers)
    print(f"✅ Generated Longhorn nodes: {output_file}")
    print(f"   Total nodes configured: {total_nodes}")
    print(f"   VM nodes: {len(all_vms)}")
    for node_name in sorted(all_vms.keys()):
        print(f"     - {node_name}")
    if baremetal_workers:
        print(f"   Bare metal nodes: {len(baremetal_workers)}")
        for node in baremetal_workers:
            print(f"     - {node.get('hostname', 'unknown')}")

if __name__ == '__main__':
    main()
