---
# Static Ansible Inventory
# Talos K8s: CP: 10.20.0.40 (VM), Worker-01: 10.20.0.41 (VM) — all on Proxmox

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Network configuration
    network_cidr: "10.20.0.0/24"
    network_gateway: "10.20.0.1"
