apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
  namespace: pnl-postgres
data:
  SITE_ID: pnl
  STORAGE_CLASS: local-path
  S3_ENDPOINT: http://minio.minio-system.svc.cluster.local:9000
  S3_BUCKET: cnpg-backups
